### PR TITLE
.NET 5 upgrade

### PR DESCRIPTION
**Pull request by davidcassell**
# Pull Request Template

## Description

.NET 5 updates

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Required Configuration on CI/CD platform

- Sample Changes

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Unit tests

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] My changes fulfill the acceptance criteria for the story or bug
- [x] I made/planned the required configuration changes on CI/CD

### CODE REVIEW

**Review by LewisPercival — APPROVED** [review]
Nice one David!

**Review by french-justin — APPROVED** [review]
Good stuff

**Review by moattarwork — CHANGES_REQUESTED** [review]
Good one. Can we rename the project back to Easify.Notifications too before this merge?

Also, remember to change the build too

**Comment by davidcassell** [comment]
> Good one. Can we rename the project back to Easify.Notifications too before this merge?
> 
> Also, remember to change the build too

👍 👍 👍 Great. I think in hindsight, that "Extensions" name change wasn't a good move, so I'm glad to revert back

**Comment by davidcassell** [comment]
> Good one. Can we rename the project back to Easify.Notifications too before this merge?
> 
> Also, remember to change the build too

This is all done and tagged to V5.0.0 with tag message to document the rename from Easify.Extensions.Notifications

**Pull request merged**
